import { useRef } from 'react'
import { Printer, Download, Share2, Calendar } from 'lucide-react'
import { Button } from '@/components/ui'

export function PrintLayout({ children, title, date }: { children: React.ReactNode, title: string, date: string }) {
    const printRef = useRef(null)

    const handlePrint = () => {
        window.print()
    }

    return (
        <div className="min-h-screen bg-slate-100 dark:bg-slate-900 p-8 print:p-0 print:bg-white">
            {/* Toolbar - Hidden in Print */}
            <div className="max-w-[210mm] mx-auto mb-6 flex justify-between items-center print:hidden">
                <Button variant="outline" className="gap-2 rounded-none bg-white dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700 dark:border-slate-700" onClick={() => window.history.back()}>
                    &larr; Back
                </Button>
                <div className="flex gap-2">
                    <Button variant="outline" className="gap-2 rounded-none bg-white dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700 dark:border-slate-700" onClick={handlePrint}>
                        <Printer className="w-4 h-4" /> Print
                    </Button>
                    <Button variant="outline" className="gap-2 rounded-none bg-white dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700 dark:border-slate-700">
                        <Download className="w-4 h-4" /> PDF
                    </Button>
                    <Button variant="outline" className="gap-2 rounded-none bg-white dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700 dark:border-slate-700">
                        <Share2 className="w-4 h-4" /> Share
                    </Button>
                </div>
            </div>

            {/* A4 Page Container */}
            <div
                ref={printRef}
                className="max-w-[210mm] min-h-[297mm] mx-auto bg-white shadow-xl print:shadow-none p-[20mm] relative"
            >
                {/* Print Headers */}
                <div className="flex justify-between items-end border-b-2 border-slate-900 pb-4 mb-8">
                    <div>
                        <h1 className="text-3xl font-black uppercase tracking-tight text-slate-900">{title}</h1>
                        <p className="text-slate-500 font-bold uppercase text-xs tracking-wider mt-1">HouseFin Man Report</p>
                    </div>
                    <div className="text-right">
                        <div className="flex items-center gap-2 text-sm font-bold text-slate-900">
                            <Calendar className="w-4 h-4" /> {date}
                        </div>
                        <p className="text-[10px] text-slate-400 mt-1 uppercase">Confidential</p>
                    </div>
                </div>

                {/* Content */}
                <div className="print:text-sm">
                    {children}
                </div>

                {/* Print Footer */}
                <div className="absolute bottom-[15mm] left-[20mm] right-[20mm] border-t border-slate-200 pt-4 flex justify-between items-center text-[10px] text-slate-400 uppercase font-bold">
                    <span>Generated by HouseFin Man AI</span>
                    <span>Page 1 of 1</span>
                </div>
            </div>
        </div>
    )
}
